function skillsMember() {
  return [
    { name: "HTML", value: 100 },
    { name: "CSS", value: 100 },
    { name: "Javascript", value: 90 },
    { name: "React", value: 90 },
    { name: "Node.js", value: 90 },
    { name: "Express.js", value: 90 },
    { name: "MongoDB", value: 90 },
    { name: "Git", value: 100 },
    { name: "Github", value: 100 },
    { name: "Bootstrap", value: 100 },
    { name: "Materialize", value: 100 },
    { name: "SASS", value: 100 },
    { name: "LESS", value: 100 },
    { name: "JQuery", value: 90 },
    { name: "AJAX", value: 90 },
    { name: "JSON", value: 100 },
    { name: "RESTful API", value: 90 },
    { name: "GraphQL", value: 90 },
    { name: "Webpack", value: 90 },
    { name: "Babel", value: 90 },
    { name: "Gulp", value: 90 },
    { name: "NPM", value: 100 },
    { name: "Yarn", value: 100 },
    { name: "Webpack", value: 90 },
    { name: "Babel", value: 90 },
    { name: "Gulp", value: 90 },
    { name: "NPM", value: 100 },
    { name: "Yarn", value: 100 },
    { name: "Web Design", value: 100 },
    { name: "Web Development", value: 100 },
    { name: "UI/UX", value: 100 },
  ];
}